# Generated by Django 5.2.5 on 2025-11-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('entidad_aseguradora', models.CharField(blank=True, max_length=255, null=True)),
                ('cups', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('prioridad_atencion', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('profesional', models.CharField(blank=True, max_length=255, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_grupo_diagnostico', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_diagnostico', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_estadificacion_dx', models.CharField(blank=True, max_length=255, null=True)),
                ('estadificacion_diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_captacion', models.DateField(blank=True, null=True)),
                ('tipo_procedimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_solicitud', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud_cita', models.DateField(blank=True, null=True)),
                ('fecha_cita', models.DateField(blank=True, null=True)),
                ('prestador', models.CharField(blank=True, max_length=255, null=True)),
                ('barrera', models.CharField(blank=True, max_length=255, null=True)),
                ('oportunidad', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('mes_ordenamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('semana_ordenamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='patients.patient')),
            ],
        ),
    ]
