# Generated by Django 5.2.5 on 2025-12-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='agrupador',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
