# Generated by Django 5.2.5 on 2025-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_followup_agrupador'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo', models.CharField(choices=[('PENDIENTE', '⚠️ PENDIENTE CLASIFICAR'), ('CONSULTA', 'CONSULTA ESPECIALIZADA'), ('QUIMIOTERAPIA', 'QUIMIOTERAPIA'), ('RADIOTERAPIA', 'RADIOTERAPIA'), ('CIRUGIA', 'CIRUGÍA'), ('IMAGEN', 'IMAGENOLOGÍA'), ('LABORATORIO', 'LABORATORIO CLÍNICO'), ('DOLOR', 'CLÍNICA DEL DOLOR'), ('ESTANCIA', 'ESTANCIA / HOSPITALIZACIÓN'), ('DIAGNOSTICO', 'PROCEDIMIENTO DIAGNÓSTICO'), ('COMPLEMENTARIO', 'SERVICIO COMPLEMENTARIO'), ('ONCOLOGIA', 'ONCOLOGÍA GENERAL'), ('OTROS', 'OTROS SERVICIOS')], default='PENDIENTE', max_length=50)),
            ],
        ),
    ]
