# Generated by Django 5.2.5 on 2025-10-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authorization',
            new_name='Authorizations',
        ),
    ]
