# Generated by Django 5.2.5 on 2025-11-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('OT', 'Otro')], max_length=5)),
                ('numero_documento', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=150, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad_residencia', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_natural', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
