# Generated by Django 5.2.5 on 2025-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta'), ('CE', 'C.E.')], max_length=10)),
                ('numero_documento', models.CharField(db_index=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=2, null=True)),
                ('eps', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_cancer', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('active', 'Activo'), ('fallecido', 'Fallecido'), ('no_acepta', 'No acepta')], default='active', max_length=20)),
            ],
            options={
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
