# Generated by Django 5.2.5 on 2025-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / Celular'),
        ),
    ]
