# Generated by Django 5.2.5 on 2025-11-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=120)),
                ('prestador', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(default='agendada', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='patients.patient')),
            ],
        ),
    ]
