# Generated by Django 5.2.5 on 2025-12-18 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='paciente',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='causa_interrupcion',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='treatment',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='frecuencia_dias',
            field=models.PositiveIntegerField(default=21, help_text='Cada cuántos días es el ciclo (ej: 21)'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='nombre_esquema',
            field=models.CharField(default='Esquema General', help_text='Ej: Esquema AC-T (Doxorrubicina + Ciclofosfamida)', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='total_ciclos',
            field=models.PositiveIntegerField(default=1, help_text='Cuántos ciclos se ordenaron'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Inicio Ciclo 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tipo',
            field=models.CharField(choices=[('QUIMIO', 'Quimioterapia'), ('RADIO', 'Radioterapia'), ('INMUNO', 'Inmunoterapia'), ('ORAL', 'Terapia Oral'), ('OTRO', 'Otro')], default='QUIMIO', max_length=20),
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='# Ciclo')),
                ('fecha_programada', models.DateField(help_text='Fecha teórica calculada')),
                ('fecha_real', models.DateField(blank=True, help_text='Cuando realmente se hizo', null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado (Teórico)'), ('AGENDADO', 'Cita Asignada'), ('REALIZADO', 'Administrado/Realizado'), ('CANCELADO', 'Cancelado/Perdido')], default='PROGRAMADO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='treatments.treatment')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
